# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trix_core', '0004_user_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=10, verbose_name='Point value'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Experience points'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
    ]
